package com.demo.common.event;

public enum TaskChangeType {
    TASK_CREATED,
    STATUS_CHANGED,
    COMMENT_ADDED,
    PHASE_CHANGED,
    PLANNED_WORK_CREATED,
    BOOKED_WORK_CREATED,
    BOOKED_WORK_UPDATED,
    BOOKED_WORK_DELETED,
    ATTACHMENT_ADDED,
    ATTACHMENT_DELETED
}
